#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJECT_DIR="$ROOT/projects/koszalin-minecraft"
# shellcheck disable=SC1091
source "$PROJECT_DIR/config.env"

BUILD_DIR="${BUILD_DIR:-$ROOT/build/koszalin-minecraft}"
TOOLS_DIR="$BUILD_DIR/tools"
WORLD_BASE="$BUILD_DIR/worlds"
DIST_DIR="$BUILD_DIR/dist"
LOG_DIR="$BUILD_DIR/logs"

rm -rf "$WORLD_BASE" "$DIST_DIR" "$LOG_DIR"
mkdir -p "$TOOLS_DIR" "$WORLD_BASE" "$DIST_DIR" "$LOG_DIR"

ARCHIVE="arnis-linux-appimage.tar.gz"
ARNIS_URL="https://github.com/louis-e/arnis/releases/download/${ARNIS_VERSION}/${ARCHIVE}"

printf '== Koszalin 1:1 Minecraft ==\n'
printf 'Arnis: %s\nBBOX: %s\nScale: %s block/m\n' "$ARNIS_VERSION" "$BBOX" "$SCALE"

df -h . || true

if [[ ! -f "$TOOLS_DIR/$ARCHIVE" ]]; then
  curl --fail --location --retry 6 --retry-all-errors --connect-timeout 30 \
    --output "$TOOLS_DIR/$ARCHIVE" "$ARNIS_URL"
fi

echo "${ARNIS_LINUX_APPIMAGE_SHA256}  $TOOLS_DIR/$ARCHIVE" | sha256sum --check --status || {
  echo "ERROR: Arnis archive checksum mismatch" >&2
  rm -f "$TOOLS_DIR/$ARCHIVE"
  exit 20
}

rm -f "$TOOLS_DIR/arnis-linux.AppImage"
tar -xzf "$TOOLS_DIR/$ARCHIVE" -C "$TOOLS_DIR"
chmod +x "$TOOLS_DIR/arnis-linux.AppImage"

export APPIMAGE_EXTRACT_AND_RUN=1
export RUST_BACKTRACE=1

set +e
"$TOOLS_DIR/arnis-linux.AppImage" \
  --output-dir="$WORLD_BASE" \
  --bbox="$BBOX" \
  --terrain \
  --scale="$SCALE" \
  --spawn-lat="$SPAWN_LAT" \
  --spawn-lng="$SPAWN_LNG" \
  --gamemode=creative \
  --world-time=6000 \
  --map-preview \
  2>&1 | tee "$LOG_DIR/arnis.log"
ARNIS_RC=${PIPESTATUS[0]}
set -e

if [[ $ARNIS_RC -ne 0 ]]; then
  echo "ERROR: Arnis exited with code $ARNIS_RC" >&2
  exit "$ARNIS_RC"
fi

LEVEL_DAT="$(find "$WORLD_BASE" -type f -name level.dat -print -quit)"
if [[ -z "$LEVEL_DAT" ]]; then
  echo "ERROR: generation finished but level.dat was not found" >&2
  find "$WORLD_BASE" -maxdepth 3 -type f | head -200 >&2 || true
  exit 30
fi

GENERATED_WORLD="$(dirname "$LEVEL_DAT")"
FINAL_WORLD="$WORLD_BASE/$WORLD_NAME"
if [[ "$GENERATED_WORLD" != "$FINAL_WORLD" ]]; then
  rm -rf "$FINAL_WORLD"
  mv "$GENERATED_WORLD" "$FINAL_WORLD"
fi

cat > "$FINAL_WORLD/KOSZALIN_BUILD_INFO.txt" <<INFO
Koszalin 1:1 for Minecraft Java Edition
Generated automatically with Arnis ${ARNIS_VERSION}
Scale: ${SCALE} block per metre
BBOX: ${BBOX}
Spawn: ${SPAWN_LAT}, ${SPAWN_LNG} (Rynek Staromiejski)
Terrain: enabled
Source geometry: OpenStreetMap / sources used by Arnis
Generated by GitHub Actions workflow in piotr1859/config
INFO

printf 'World generated at: %s\n' "$FINAL_WORLD"
du -sh "$FINAL_WORLD" || true
